### ISSUE TITLE
where is the hyperplane equation(w' and b)

### ISSUE THREAD

**Issue by EvergreenHZ** [cjlin1/libsvm#115]
I am new to SVM, but as I know, SVM tries to find a best hyperplane whose equation is w'x + b = 0 to separate two classes samples. And I want to know where are the w and b after I train the hear_scale.model.

**Comment by cjlin1** [comment]
see the following libsvm faq:

Q: How could I generate the primal variable w of linear SVM?

Let's start from the binary class and assume you have two labels -1 and +1.
After obtaining the model from calling svmtrain, do the following to have w
and b:

w = model.SVs' * model.sv_coef;
b = -model.rho;

if model.Label(1) == -1
  w = -w;
  b = -b;
end

If you do regression or one-class SVM, then the if statement is not needed.

For multi-class SVM, we illustrate the setting in the following example of
running the iris data, which have 3 classes

> [y, x] = libsvmread('../../htdocs/libsvmtools/datasets/multiclass/iris.scale');
> m = svmtrain(y, x, '-t 0')

m = 

    Parameters: [5x1 double]
      nr_class: 3
       totalSV: 42
           rho: [3x1 double]
         Label: [3x1 double]
         ProbA: []
         ProbB: []
           nSV: [3x1 double]
       sv_coef: [42x2 double]
           SVs: [42x4 double]

sv_coef is like:

+-+-+--------------------+
|1|1|                    |
|v|v|  SVs from class 1  |
|2|3|                    |
+-+-+--------------------+
|1|2|                    |
|v|v|  SVs from class 2  |
|2|3|                    |
+-+-+--------------------+
|1|2|                    |
|v|v|  SVs from class 3  |
|3|3|                    |
+-+-+--------------------+

so we need to see nSV of each classes.

> m.nSV

ans =

     3
    21
    18

Suppose the goal is to find the vector w of classes 1 vs 3. Then y_i alpha_i
of training 1 vs 3 are

> coef = [m.sv_coef(1:3,2); m.sv_coef(25:42,1)];

and SVs are:

> SVs = [m.SVs(1:3,:); m.SVs(25:42,:)];

Hence, w is

> w = SVs'*coef;

For rho,

> m.rho

ans =

    1.1465
    0.3682
   -1.9969
> b = -m.rho(2);

because rho is arranged by 1vs2 1vs3 2vs3.


EvergreenHZ writes:
